"""Init

Revision ID: 250b4e8a5d48
Revises: 544cdedc5487
Create Date: 2023-10-17 22:54:23.791644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b4e8a5d48'
down_revision = '544cdedc5487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
