"""Init

Revision ID: 544cdedc5487
Revises: 8c5bc494077f
Create Date: 2023-10-17 22:42:45.217297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544cdedc5487'
down_revision = '8c5bc494077f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
