"""Init

Revision ID: 601b9fc03d56
Revises: 963b2abe1b4c
Create Date: 2023-10-02 15:33:49.890503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601b9fc03d56'
down_revision = '963b2abe1b4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
