"""Init

Revision ID: 8c5bc494077f
Revises: 601b9fc03d56
Create Date: 2023-10-17 22:04:38.347633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5bc494077f'
down_revision = '601b9fc03d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
